using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;

namespace FrontierPros.Data.Migrations
{
    public partial class AddedTimeZoneDataTable : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "tblTimeZoneData",
                columns: table => new
                {
                    Id = table.Column<int>(nullable: false)
                        .Annotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn),
                    StandardName = table.Column<string>(maxLength: 255, nullable: false),
                    TimeZoneId = table.Column<string>(maxLength: 255, nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_tblTimeZoneData", x => x.Id);
                });

			migrationBuilder.Sql(@"
									GO
									SET IDENTITY_INSERT [dbo].[tblTimeZoneData] ON 

									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (1, N'Europe/Andorra', N'Europe/Andorra')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (2, N'Asia/Dubai', N'Asia/Dubai')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (3, N'Asia/Kabul', N'Asia/Kabul')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (4, N'America/Antigua', N'America/Antigua')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (5, N'America/Anguilla', N'America/Anguilla')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (6, N'Europe/Tirane', N'Europe/Tirane')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (7, N'Asia/Yerevan', N'Asia/Yerevan')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (8, N'Africa/Luanda', N'Africa/Luanda')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (9, N'Antarctica/McMurdo', N'Antarctica/McMurdo')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (10, N'Antarctica/Casey', N'Antarctica/Casey')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (11, N'Antarctica/Davis', N'Antarctica/Davis')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (12, N'Antarctica/DumontDUrville', N'Antarctica/DumontDUrville')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (13, N'Antarctica/Mawson', N'Antarctica/Mawson')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (14, N'Antarctica/Palmer', N'Antarctica/Palmer')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (15, N'Antarctica/Rothera', N'Antarctica/Rothera')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (16, N'Antarctica/Syowa', N'Antarctica/Syowa')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (17, N'Antarctica/Troll', N'Antarctica/Troll')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (18, N'Antarctica/Vostok', N'Antarctica/Vostok')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (19, N'Argentina/Buenos Aires', N'America/Argentina/Buenos_Aires')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (20, N'Argentina/Cordoba', N'America/Argentina/Cordoba')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (21, N'Argentina/Salta', N'America/Argentina/Salta')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (22, N'Argentina/Jujuy', N'America/Argentina/Jujuy')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (23, N'Argentina/Tucuman', N'America/Argentina/Tucuman')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (24, N'Argentina/Catamarca', N'America/Argentina/Catamarca')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (25, N'Argentina/La Rioja', N'America/Argentina/La_Rioja')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (26, N'Argentina/San Juan', N'America/Argentina/San_Juan')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (27, N'Argentina/Mendoza', N'America/Argentina/Mendoza')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (28, N'Argentina/San Luis', N'America/Argentina/San_Luis')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (29, N'Argentina/Rio Gallegos', N'America/Argentina/Rio_Gallegos')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (30, N'Argentina/Ushuaia', N'America/Argentina/Ushuaia')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (31, N'Pacific/Pago Pago', N'Pacific/Pago_Pago')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (32, N'Europe/Vienna', N'Europe/Vienna')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (33, N'Australia/Lord Howe', N'Australia/Lord_Howe')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (34, N'Antarctica/Macquarie', N'Antarctica/Macquarie')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (35, N'Australia/Hobart', N'Australia/Hobart')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (36, N'Australia/Currie', N'Australia/Currie')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (37, N'Australia/Melbourne', N'Australia/Melbourne')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (38, N'Australia/Sydney', N'Australia/Sydney')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (39, N'Australia/Broken Hill', N'Australia/Broken_Hill')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (40, N'Australia/Brisbane', N'Australia/Brisbane')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (41, N'Australia/Lindeman', N'Australia/Lindeman')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (42, N'Australia/Adelaide', N'Australia/Adelaide')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (43, N'Australia/Darwin', N'Australia/Darwin')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (44, N'Australia/Perth', N'Australia/Perth')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (45, N'Australia/Eucla', N'Australia/Eucla')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (46, N'America/Aruba', N'America/Aruba')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (47, N'Europe/Mariehamn', N'Europe/Mariehamn')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (48, N'Asia/Baku', N'Asia/Baku')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (49, N'Europe/Sarajevo', N'Europe/Sarajevo')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (50, N'America/Barbados', N'America/Barbados')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (51, N'Asia/Dhaka', N'Asia/Dhaka')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (52, N'Europe/Brussels', N'Europe/Brussels')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (53, N'Africa/Ouagadougou', N'Africa/Ouagadougou')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (54, N'Europe/Sofia', N'Europe/Sofia')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (55, N'Asia/Bahrain', N'Asia/Bahrain')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (56, N'Africa/Bujumbura', N'Africa/Bujumbura')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (57, N'Africa/Porto-Novo', N'Africa/Porto-Novo')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (58, N'America/St Barthelemy', N'America/St_Barthelemy')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (59, N'Atlantic/Bermuda', N'Atlantic/Bermuda')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (60, N'Asia/Brunei', N'Asia/Brunei')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (61, N'America/La Paz', N'America/La_Paz')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (62, N'America/Kralendijk', N'America/Kralendijk')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (63, N'America/Noronha', N'America/Noronha')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (64, N'America/Belem', N'America/Belem')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (65, N'America/Fortaleza', N'America/Fortaleza')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (66, N'America/Recife', N'America/Recife')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (67, N'America/Araguaina', N'America/Araguaina')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (68, N'America/Maceio', N'America/Maceio')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (69, N'America/Bahia', N'America/Bahia')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (70, N'America/Sao Paulo', N'America/Sao_Paulo')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (71, N'America/Campo Grande', N'America/Campo_Grande')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (72, N'America/Cuiaba', N'America/Cuiaba')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (73, N'America/Santarem', N'America/Santarem')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (74, N'America/Porto Velho', N'America/Porto_Velho')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (75, N'America/Boa Vista', N'America/Boa_Vista')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (76, N'America/Manaus', N'America/Manaus')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (77, N'America/Eirunepe', N'America/Eirunepe')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (78, N'America/Rio Branco', N'America/Rio_Branco')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (79, N'America/Nassau', N'America/Nassau')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (80, N'Asia/Thimphu', N'Asia/Thimphu')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (81, N'Africa/Gaborone', N'Africa/Gaborone')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (82, N'Europe/Minsk', N'Europe/Minsk')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (83, N'America/Belize', N'America/Belize')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (84, N'America/St Johns', N'America/St_Johns')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (85, N'America/Halifax', N'America/Halifax')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (86, N'America/Glace Bay', N'America/Glace_Bay')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (87, N'America/Moncton', N'America/Moncton')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (88, N'America/Goose Bay', N'America/Goose_Bay')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (89, N'America/Blanc-Sablon', N'America/Blanc-Sablon')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (90, N'America/Toronto', N'America/Toronto')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (91, N'America/Nipigon', N'America/Nipigon')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (92, N'America/Thunder Bay', N'America/Thunder_Bay')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (93, N'America/Iqaluit', N'America/Iqaluit')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (94, N'America/Pangnirtung', N'America/Pangnirtung')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (95, N'America/Atikokan', N'America/Atikokan')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (96, N'America/Winnipeg', N'America/Winnipeg')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (97, N'America/Rainy River', N'America/Rainy_River')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (98, N'America/Resolute', N'America/Resolute')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (99, N'America/Rankin Inlet', N'America/Rankin_Inlet')
									GO
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (100, N'America/Regina', N'America/Regina')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (101, N'America/Swift Current', N'America/Swift_Current')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (102, N'America/Edmonton', N'America/Edmonton')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (103, N'America/Cambridge Bay', N'America/Cambridge_Bay')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (104, N'America/Yellowknife', N'America/Yellowknife')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (105, N'America/Inuvik', N'America/Inuvik')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (106, N'America/Creston', N'America/Creston')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (107, N'America/Dawson Creek', N'America/Dawson_Creek')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (108, N'America/Fort Nelson', N'America/Fort_Nelson')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (109, N'America/Vancouver', N'America/Vancouver')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (110, N'America/Whitehorse', N'America/Whitehorse')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (111, N'America/Dawson', N'America/Dawson')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (112, N'Indian/Cocos', N'Indian/Cocos')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (113, N'Africa/Kinshasa', N'Africa/Kinshasa')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (114, N'Africa/Lubumbashi', N'Africa/Lubumbashi')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (115, N'Africa/Bangui', N'Africa/Bangui')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (116, N'Africa/Brazzaville', N'Africa/Brazzaville')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (117, N'Europe/Zurich', N'Europe/Zurich')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (118, N'Africa/Abidjan', N'Africa/Abidjan')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (119, N'Pacific/Rarotonga', N'Pacific/Rarotonga')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (120, N'America/Santiago', N'America/Santiago')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (121, N'America/Punta Arenas', N'America/Punta_Arenas')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (122, N'Pacific/Easter', N'Pacific/Easter')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (123, N'Africa/Douala', N'Africa/Douala')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (124, N'Asia/Shanghai', N'Asia/Shanghai')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (125, N'Asia/Urumqi', N'Asia/Urumqi')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (126, N'America/Bogota', N'America/Bogota')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (127, N'America/Costa Rica', N'America/Costa_Rica')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (128, N'America/Havana', N'America/Havana')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (129, N'Atlantic/Cape Verde', N'Atlantic/Cape_Verde')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (130, N'America/Curacao', N'America/Curacao')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (131, N'Indian/Christmas', N'Indian/Christmas')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (132, N'Asia/Nicosia', N'Asia/Nicosia')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (133, N'Asia/Famagusta', N'Asia/Famagusta')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (134, N'Europe/Prague', N'Europe/Prague')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (135, N'Europe/Berlin', N'Europe/Berlin')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (136, N'Europe/Busingen', N'Europe/Busingen')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (137, N'Africa/Djibouti', N'Africa/Djibouti')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (138, N'Europe/Copenhagen', N'Europe/Copenhagen')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (139, N'America/Dominica', N'America/Dominica')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (140, N'America/Santo Domingo', N'America/Santo_Domingo')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (141, N'Africa/Algiers', N'Africa/Algiers')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (142, N'America/Guayaquil', N'America/Guayaquil')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (143, N'Pacific/Galapagos', N'Pacific/Galapagos')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (144, N'Europe/Tallinn', N'Europe/Tallinn')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (145, N'Africa/Cairo', N'Africa/Cairo')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (146, N'Africa/El Aaiun', N'Africa/El_Aaiun')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (147, N'Africa/Asmara', N'Africa/Asmara')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (148, N'Europe/Madrid', N'Europe/Madrid')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (149, N'Africa/Ceuta', N'Africa/Ceuta')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (150, N'Atlantic/Canary', N'Atlantic/Canary')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (151, N'Africa/Addis Ababa', N'Africa/Addis_Ababa')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (152, N'Europe/Helsinki', N'Europe/Helsinki')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (153, N'Pacific/Fiji', N'Pacific/Fiji')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (154, N'Atlantic/Stanley', N'Atlantic/Stanley')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (155, N'Pacific/Chuuk', N'Pacific/Chuuk')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (156, N'Pacific/Pohnpei', N'Pacific/Pohnpei')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (157, N'Pacific/Kosrae', N'Pacific/Kosrae')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (158, N'Atlantic/Faroe', N'Atlantic/Faroe')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (159, N'Europe/Paris', N'Europe/Paris')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (160, N'Africa/Libreville', N'Africa/Libreville')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (161, N'Europe/London', N'Europe/London')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (162, N'America/Grenada', N'America/Grenada')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (163, N'Asia/Tbilisi', N'Asia/Tbilisi')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (164, N'America/Cayenne', N'America/Cayenne')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (165, N'Europe/Guernsey', N'Europe/Guernsey')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (166, N'Africa/Accra', N'Africa/Accra')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (167, N'Europe/Gibraltar', N'Europe/Gibraltar')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (168, N'America/Godthab', N'America/Godthab')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (169, N'America/Danmarkshavn', N'America/Danmarkshavn')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (170, N'America/Scoresbysund', N'America/Scoresbysund')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (171, N'America/Thule', N'America/Thule')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (172, N'Africa/Banjul', N'Africa/Banjul')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (173, N'Africa/Conakry', N'Africa/Conakry')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (174, N'America/Guadeloupe', N'America/Guadeloupe')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (175, N'Africa/Malabo', N'Africa/Malabo')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (176, N'Europe/Athens', N'Europe/Athens')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (177, N'Atlantic/South Georgia', N'Atlantic/South_Georgia')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (178, N'America/Guatemala', N'America/Guatemala')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (179, N'Pacific/Guam', N'Pacific/Guam')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (180, N'Africa/Bissau', N'Africa/Bissau')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (181, N'America/Guyana', N'America/Guyana')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (182, N'Asia/Hong Kong', N'Asia/Hong_Kong')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (183, N'America/Tegucigalpa', N'America/Tegucigalpa')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (184, N'Europe/Zagreb', N'Europe/Zagreb')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (185, N'America/Port-au-Prince', N'America/Port-au-Prince')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (186, N'Europe/Budapest', N'Europe/Budapest')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (187, N'Asia/Jakarta', N'Asia/Jakarta')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (188, N'Asia/Pontianak', N'Asia/Pontianak')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (189, N'Asia/Makassar', N'Asia/Makassar')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (190, N'Asia/Jayapura', N'Asia/Jayapura')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (191, N'Europe/Dublin', N'Europe/Dublin')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (192, N'Asia/Jerusalem', N'Asia/Jerusalem')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (193, N'Europe/Isle of Man', N'Europe/Isle_of_Man')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (194, N'Asia/Kolkata', N'Asia/Kolkata')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (195, N'Indian/Chagos', N'Indian/Chagos')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (196, N'Asia/Baghdad', N'Asia/Baghdad')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (197, N'Asia/Tehran', N'Asia/Tehran')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (198, N'Atlantic/Reykjavik', N'Atlantic/Reykjavik')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (199, N'Europe/Rome', N'Europe/Rome')
									GO
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (200, N'Europe/Jersey', N'Europe/Jersey')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (201, N'America/Jamaica', N'America/Jamaica')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (202, N'Asia/Amman', N'Asia/Amman')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (203, N'Asia/Tokyo', N'Asia/Tokyo')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (204, N'Africa/Nairobi', N'Africa/Nairobi')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (205, N'Asia/Bishkek', N'Asia/Bishkek')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (206, N'Asia/Phnom Penh', N'Asia/Phnom_Penh')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (207, N'Pacific/Tarawa', N'Pacific/Tarawa')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (208, N'Pacific/Enderbury', N'Pacific/Enderbury')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (209, N'Pacific/Kiritimati', N'Pacific/Kiritimati')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (210, N'Indian/Comoro', N'Indian/Comoro')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (211, N'America/St Kitts', N'America/St_Kitts')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (212, N'Asia/Pyongyang', N'Asia/Pyongyang')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (213, N'Asia/Seoul', N'Asia/Seoul')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (214, N'Asia/Kuwait', N'Asia/Kuwait')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (215, N'America/Cayman', N'America/Cayman')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (216, N'Asia/Almaty', N'Asia/Almaty')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (217, N'Asia/Qyzylorda', N'Asia/Qyzylorda')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (218, N'Asia/Aqtobe', N'Asia/Aqtobe')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (219, N'Asia/Aqtau', N'Asia/Aqtau')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (220, N'Asia/Atyrau', N'Asia/Atyrau')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (221, N'Asia/Oral', N'Asia/Oral')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (222, N'Asia/Vientiane', N'Asia/Vientiane')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (223, N'Asia/Beirut', N'Asia/Beirut')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (224, N'America/St Lucia', N'America/St_Lucia')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (225, N'Europe/Vaduz', N'Europe/Vaduz')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (226, N'Asia/Colombo', N'Asia/Colombo')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (227, N'Africa/Monrovia', N'Africa/Monrovia')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (228, N'Africa/Maseru', N'Africa/Maseru')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (229, N'Europe/Vilnius', N'Europe/Vilnius')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (230, N'Europe/Luxembourg', N'Europe/Luxembourg')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (231, N'Europe/Riga', N'Europe/Riga')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (232, N'Africa/Tripoli', N'Africa/Tripoli')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (233, N'Africa/Casablanca', N'Africa/Casablanca')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (234, N'Europe/Monaco', N'Europe/Monaco')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (235, N'Europe/Chisinau', N'Europe/Chisinau')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (236, N'Europe/Podgorica', N'Europe/Podgorica')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (237, N'America/Marigot', N'America/Marigot')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (238, N'Indian/Antananarivo', N'Indian/Antananarivo')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (239, N'Pacific/Majuro', N'Pacific/Majuro')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (240, N'Pacific/Kwajalein', N'Pacific/Kwajalein')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (241, N'Europe/Skopje', N'Europe/Skopje')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (242, N'Africa/Bamako', N'Africa/Bamako')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (243, N'Asia/Yangon', N'Asia/Yangon')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (244, N'Asia/Ulaanbaatar', N'Asia/Ulaanbaatar')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (245, N'Asia/Hovd', N'Asia/Hovd')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (246, N'Asia/Choibalsan', N'Asia/Choibalsan')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (247, N'Asia/Macau', N'Asia/Macau')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (248, N'Pacific/Saipan', N'Pacific/Saipan')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (249, N'America/Martinique', N'America/Martinique')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (250, N'Africa/Nouakchott', N'Africa/Nouakchott')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (251, N'America/Montserrat', N'America/Montserrat')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (252, N'Europe/Malta', N'Europe/Malta')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (253, N'Indian/Mauritius', N'Indian/Mauritius')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (254, N'Indian/Maldives', N'Indian/Maldives')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (255, N'Africa/Blantyre', N'Africa/Blantyre')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (256, N'America/Mexico City', N'America/Mexico_City')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (257, N'America/Cancun', N'America/Cancun')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (258, N'America/Merida', N'America/Merida')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (259, N'America/Monterrey', N'America/Monterrey')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (260, N'America/Matamoros', N'America/Matamoros')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (261, N'America/Mazatlan', N'America/Mazatlan')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (262, N'America/Chihuahua', N'America/Chihuahua')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (263, N'America/Ojinaga', N'America/Ojinaga')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (264, N'America/Hermosillo', N'America/Hermosillo')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (265, N'America/Tijuana', N'America/Tijuana')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (266, N'America/Bahia Banderas', N'America/Bahia_Banderas')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (267, N'Asia/Kuala Lumpur', N'Asia/Kuala_Lumpur')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (268, N'Asia/Kuching', N'Asia/Kuching')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (269, N'Africa/Maputo', N'Africa/Maputo')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (270, N'Africa/Windhoek', N'Africa/Windhoek')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (271, N'Pacific/Noumea', N'Pacific/Noumea')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (272, N'Africa/Niamey', N'Africa/Niamey')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (273, N'Pacific/Norfolk', N'Pacific/Norfolk')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (274, N'Africa/Lagos', N'Africa/Lagos')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (275, N'America/Managua', N'America/Managua')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (276, N'Europe/Amsterdam', N'Europe/Amsterdam')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (277, N'Europe/Oslo', N'Europe/Oslo')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (278, N'Asia/Kathmandu', N'Asia/Kathmandu')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (279, N'Pacific/Nauru', N'Pacific/Nauru')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (280, N'Pacific/Niue', N'Pacific/Niue')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (281, N'Pacific/Auckland', N'Pacific/Auckland')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (282, N'Pacific/Chatham', N'Pacific/Chatham')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (283, N'Asia/Muscat', N'Asia/Muscat')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (284, N'America/Panama', N'America/Panama')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (285, N'America/Lima', N'America/Lima')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (286, N'Pacific/Tahiti', N'Pacific/Tahiti')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (287, N'Pacific/Marquesas', N'Pacific/Marquesas')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (288, N'Pacific/Gambier', N'Pacific/Gambier')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (289, N'Pacific/Port Moresby', N'Pacific/Port_Moresby')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (290, N'Pacific/Bougainville', N'Pacific/Bougainville')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (291, N'Asia/Manila', N'Asia/Manila')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (292, N'Asia/Karachi', N'Asia/Karachi')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (293, N'Europe/Warsaw', N'Europe/Warsaw')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (294, N'America/Miquelon', N'America/Miquelon')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (295, N'Pacific/Pitcairn', N'Pacific/Pitcairn')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (296, N'America/Puerto Rico', N'America/Puerto_Rico')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (297, N'Asia/Gaza', N'Asia/Gaza')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (298, N'Asia/Hebron', N'Asia/Hebron')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (299, N'Europe/Lisbon', N'Europe/Lisbon')
									GO
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (300, N'Atlantic/Madeira', N'Atlantic/Madeira')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (301, N'Atlantic/Azores', N'Atlantic/Azores')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (302, N'Pacific/Palau', N'Pacific/Palau')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (303, N'America/Asuncion', N'America/Asuncion')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (304, N'Asia/Qatar', N'Asia/Qatar')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (305, N'Indian/Reunion', N'Indian/Reunion')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (306, N'Europe/Bucharest', N'Europe/Bucharest')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (307, N'Europe/Belgrade', N'Europe/Belgrade')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (308, N'Europe/Kaliningrad', N'Europe/Kaliningrad')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (309, N'Europe/Moscow', N'Europe/Moscow')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (310, N'Europe/Simferopol', N'Europe/Simferopol')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (311, N'Europe/Volgograd', N'Europe/Volgograd')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (312, N'Europe/Kirov', N'Europe/Kirov')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (313, N'Europe/Astrakhan', N'Europe/Astrakhan')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (314, N'Europe/Saratov', N'Europe/Saratov')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (315, N'Europe/Ulyanovsk', N'Europe/Ulyanovsk')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (316, N'Europe/Samara', N'Europe/Samara')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (317, N'Asia/Yekaterinburg', N'Asia/Yekaterinburg')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (318, N'Asia/Omsk', N'Asia/Omsk')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (319, N'Asia/Novosibirsk', N'Asia/Novosibirsk')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (320, N'Asia/Barnaul', N'Asia/Barnaul')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (321, N'Asia/Tomsk', N'Asia/Tomsk')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (322, N'Asia/Novokuznetsk', N'Asia/Novokuznetsk')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (323, N'Asia/Krasnoyarsk', N'Asia/Krasnoyarsk')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (324, N'Asia/Irkutsk', N'Asia/Irkutsk')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (325, N'Asia/Chita', N'Asia/Chita')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (326, N'Asia/Yakutsk', N'Asia/Yakutsk')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (327, N'Asia/Khandyga', N'Asia/Khandyga')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (328, N'Asia/Vladivostok', N'Asia/Vladivostok')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (329, N'Asia/Ust-Nera', N'Asia/Ust-Nera')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (330, N'Asia/Magadan', N'Asia/Magadan')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (331, N'Asia/Sakhalin', N'Asia/Sakhalin')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (332, N'Asia/Srednekolymsk', N'Asia/Srednekolymsk')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (333, N'Asia/Kamchatka', N'Asia/Kamchatka')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (334, N'Asia/Anadyr', N'Asia/Anadyr')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (335, N'Africa/Kigali', N'Africa/Kigali')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (336, N'Asia/Riyadh', N'Asia/Riyadh')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (337, N'Pacific/Guadalcanal', N'Pacific/Guadalcanal')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (338, N'Indian/Mahe', N'Indian/Mahe')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (339, N'Africa/Khartoum', N'Africa/Khartoum')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (340, N'Europe/Stockholm', N'Europe/Stockholm')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (341, N'Asia/Singapore', N'Asia/Singapore')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (342, N'Atlantic/St Helena', N'Atlantic/St_Helena')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (343, N'Europe/Ljubljana', N'Europe/Ljubljana')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (344, N'Arctic/Longyearbyen', N'Arctic/Longyearbyen')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (345, N'Europe/Bratislava', N'Europe/Bratislava')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (346, N'Africa/Freetown', N'Africa/Freetown')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (347, N'Europe/San Marino', N'Europe/San_Marino')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (348, N'Africa/Dakar', N'Africa/Dakar')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (349, N'Africa/Mogadishu', N'Africa/Mogadishu')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (350, N'America/Paramaribo', N'America/Paramaribo')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (351, N'Africa/Juba', N'Africa/Juba')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (352, N'Africa/Sao Tome', N'Africa/Sao_Tome')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (353, N'America/El Salvador', N'America/El_Salvador')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (354, N'America/Lower Princes', N'America/Lower_Princes')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (355, N'Asia/Damascus', N'Asia/Damascus')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (356, N'Africa/Mbabane', N'Africa/Mbabane')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (357, N'America/Grand Turk', N'America/Grand_Turk')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (358, N'Africa/Ndjamena', N'Africa/Ndjamena')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (359, N'Indian/Kerguelen', N'Indian/Kerguelen')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (360, N'Africa/Lome', N'Africa/Lome')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (361, N'Asia/Bangkok', N'Asia/Bangkok')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (362, N'Asia/Dushanbe', N'Asia/Dushanbe')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (363, N'Pacific/Fakaofo', N'Pacific/Fakaofo')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (364, N'Asia/Dili', N'Asia/Dili')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (365, N'Asia/Ashgabat', N'Asia/Ashgabat')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (366, N'Africa/Tunis', N'Africa/Tunis')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (367, N'Pacific/Tongatapu', N'Pacific/Tongatapu')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (368, N'Europe/Istanbul', N'Europe/Istanbul')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (369, N'America/Port of Spain', N'America/Port_of_Spain')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (370, N'Pacific/Funafuti', N'Pacific/Funafuti')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (371, N'Asia/Taipei', N'Asia/Taipei')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (372, N'Africa/Dar es Salaam', N'Africa/Dar_es_Salaam')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (373, N'Europe/Kiev', N'Europe/Kiev')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (374, N'Europe/Uzhgorod', N'Europe/Uzhgorod')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (375, N'Europe/Zaporozhye', N'Europe/Zaporozhye')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (376, N'Africa/Kampala', N'Africa/Kampala')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (377, N'Pacific/Midway', N'Pacific/Midway')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (378, N'Pacific/Wake', N'Pacific/Wake')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (379, N'America/New York', N'America/New_York')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (380, N'America/Detroit', N'America/Detroit')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (381, N'America/Kentucky/Louisville', N'America/Kentucky/Louisville')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (382, N'America/Kentucky/Monticello', N'America/Kentucky/Monticello')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (383, N'America/Indiana/Indianapolis', N'America/Indiana/Indianapolis')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (384, N'America/Indiana/Vincennes', N'America/Indiana/Vincennes')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (385, N'America/Indiana/Winamac', N'America/Indiana/Winamac')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (386, N'America/Indiana/Marengo', N'America/Indiana/Marengo')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (387, N'America/Indiana/Petersburg', N'America/Indiana/Petersburg')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (388, N'America/Indiana/Vevay', N'America/Indiana/Vevay')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (389, N'America/Chicago', N'America/Chicago')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (390, N'America/Indiana/Tell City', N'America/Indiana/Tell_City')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (391, N'America/Indiana/Knox', N'America/Indiana/Knox')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (392, N'America/Menominee', N'America/Menominee')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (393, N'America/North Dakota/Center', N'America/North_Dakota/Center')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (394, N'America/North Dakota/New Salem', N'America/North_Dakota/New_Salem')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (395, N'America/North Dakota/Beulah', N'America/North_Dakota/Beulah')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (396, N'America/Denver', N'America/Denver')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (397, N'America/Boise', N'America/Boise')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (398, N'America/Phoenix', N'America/Phoenix')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (399, N'America/Los Angeles', N'America/Los_Angeles')
									GO
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (400, N'America/Anchorage', N'America/Anchorage')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (401, N'America/Juneau', N'America/Juneau')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (402, N'America/Sitka', N'America/Sitka')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (403, N'America/Metlakatla', N'America/Metlakatla')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (404, N'America/Yakutat', N'America/Yakutat')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (405, N'America/Nome', N'America/Nome')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (406, N'America/Adak', N'America/Adak')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (407, N'Pacific/Honolulu', N'Pacific/Honolulu')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (408, N'America/Montevideo', N'America/Montevideo')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (409, N'Asia/Samarkand', N'Asia/Samarkand')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (410, N'Asia/Tashkent', N'Asia/Tashkent')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (411, N'Europe/Vatican', N'Europe/Vatican')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (412, N'America/St Vincent', N'America/St_Vincent')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (413, N'America/Caracas', N'America/Caracas')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (414, N'America/Tortola', N'America/Tortola')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (415, N'America/St Thomas', N'America/St_Thomas')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (416, N'Asia/Ho Chi Minh', N'Asia/Ho_Chi_Minh')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (417, N'Pacific/Efate', N'Pacific/Efate')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (418, N'Pacific/Wallis', N'Pacific/Wallis')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (419, N'Pacific/Apia', N'Pacific/Apia')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (420, N'Asia/Aden', N'Asia/Aden')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (421, N'Indian/Mayotte', N'Indian/Mayotte')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (422, N'Africa/Johannesburg', N'Africa/Johannesburg')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (423, N'Africa/Lusaka', N'Africa/Lusaka')
									INSERT [dbo].[tblTimeZoneData] ([Id], [StandardName], [TimeZoneId]) VALUES (424, N'Africa/Harare', N'Africa/Harare')
									SET IDENTITY_INSERT [dbo].[tblTimeZoneData] OFF
									");
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "tblTimeZoneData");
        }
    }
}
